# Generated by Django 3.0.2 on 2020-01-05 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=500)),
                ('priority', models.CharField(choices=[('l', 'LOW'), ('m', 'Medium'), ('h', 'Hight')], max_length=1)),
                ('level', models.IntegerField(choices=[(-1, 'TODO'), (0, 'Doing'), (1, 'Done')])),
                ('create_date', models.DateField(default=datetime.datetime(2020, 1, 5, 16, 30, 43, 936884, tzinfo=utc))),
                ('due_date', models.DateField(default=datetime.datetime(2020, 1, 6, 16, 30, 43, 936904, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
